project 'localyyz.xcodeproj/'
platform :ios, '10.3'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'localyyz' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for localyyz

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'

  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'Stripe'

  target 'localyyzTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
